Repository balsa-sarenac/mbrs, pull requests merged in 2021-07, with the labels that each got.

#22 Refactor model generator
  PluginDevelopment/resources/ProjectOptions.xml
  PluginDevelopment/resources/templates/ejbclass.ftl
  PluginDevelopment/resources/templates/model.ftl
  PluginDevelopment/src-test/testTemplates/TestPackageGeneration.java
  PluginDevelopment/src/myplugin/analyzer/ModelAnalyzer.java
  PluginDevelopment/src/myplugin/analyzer/PropertyAnalyzer.java
  PluginDevelopment/src/myplugin/generator/BasicGenerator.java
  PluginDevelopment/src/myplugin/generator/GeneratorFactory.java
  PluginDevelopment/src/myplugin/generator/ModelGenerator.java
  PluginDevelopment/src/myplugin/generator/fmmodel/CascadeType.java
  PluginDevelopment/src/myplugin/generator/fmmodel/FMClass.java
  PluginDevelopment/src/myplugin/generator/fmmodel/FMEnumeration.java
  PluginDevelopment/src/myplugin/generator/fmmodel/FMPeristentProperty.java
  PluginDevelopment/src/myplugin/generator/fmmodel/FMProperty.java
  PluginDevelopment/src/myplugin/generator/fmmodel/FMReferencedProperty.java
  PluginDevelopment/src/myplugin/generator/fmmodel/FMType.java
  PluginDevelopment/src/myplugin/generator/fmmodel/FetchType.java
  PluginDevelopment/src/myplugin/generator/fmmodel/StrategyType.java
  fast-commerc/fast-commerc.mdzip
Labels: enhancement, refactoring

#26 Refactoring list elements and adding stereotypes to model
  PluginDevelopment/resources/templates/frontend/src/components/forms/form.ftl
  fast-commerc/mbrs-example.mdzip
Labels: enhancement, refactoring

#23 Generating DTOs
  PluginDevelopment/resources/ProjectOptions.xml
  PluginDevelopment/resources/templates/backend/abstractDTO.ftl
  PluginDevelopment/resources/templates/backend/concreteDTO.ftl
  PluginDevelopment/resources/templates/backend/model.ftl
  PluginDevelopment/src/myplugin/generator/AbstractDTOGenerator.java
  PluginDevelopment/src/myplugin/generator/ConcreteDTOGenerator.java
  PluginDevelopment/src/myplugin/generator/GeneratorFactory.java
Labels: enhancement

#25 feat: Generating backend static files
  PluginDevelopment/resources/ProjectOptions.xml
  PluginDevelopment/resources/static/backend/DemoApplication.java
  PluginDevelopment/resources/static/backend/MavenWrapperDownloader.java
  PluginDevelopment/resources/static/backend/README.md
  PluginDevelopment/resources/static/backend/backend.gitignore
  PluginDevelopment/resources/static/backend/maven-wrapper.properties
  PluginDevelopment/resources/static/backend/mvnw
  PluginDevelopment/resources/static/backend/mvnw.cmd
  PluginDevelopment/resources/templates/backend/appProperties.ftl
  PluginDevelopment/resources/templates/backend/pom.ftl
  PluginDevelopment/src/myplugin/generator/GeneratorFactory.java
  PluginDevelopment/src/myplugin/generator/config/AppPropertiesGenerator.java
  PluginDevelopment/src/myplugin/generator/config/PomXMLGenerator.java
Labels: enhancement

#27 feat: generating repositories for persistent entities
  PluginDevelopment/resources/ProjectOptions.xml
  PluginDevelopment/resources/templates/backend/repository.ftl
  PluginDevelopment/src/myplugin/generator/GeneratorFactory.java
  PluginDevelopment/src/myplugin/generator/RepositoryGenerator.java
Labels: enhancement

#29 bugfix: add missing closing xml tag
  PluginDevelopment/resources/ProjectOptions.xml
Labels: bug

#31 Feature generate get/delete api
  PluginDevelopment/resources/ProjectOptions.xml
  PluginDevelopment/resources/static/backend/exception/ExceptionResolver.java
  PluginDevelopment/resources/static/backend/exception/NotFoundException.java
  PluginDevelopment/resources/templates/backend/controller/abstractController.ftl
  PluginDevelopment/resources/templates/backend/controller/controller.ftl
  PluginDevelopment/resources/templates/backend/dto/abstractDTO.ftl
  PluginDevelopment/resources/templates/backend/dto/concreteDTO.ftl
  PluginDevelopment/resources/templates/backend/repository/repository.ftl
  PluginDevelopment/resources/templates/backend/service/abstractService.ftl
  PluginDevelopment/resources/templates/backend/service/service.ftl
  PluginDevelopment/src-test/testTemplates/TestPackageGeneration.java
  PluginDevelopment/src/myplugin/generator/GeneratorFactory.java
  PluginDevelopment/src/myplugin/generator/backend/AbstractControllerGenerator.java
  PluginDevelopment/src/myplugin/generator/backend/AbstractDTOGenerator.java
  PluginDevelopment/src/myplugin/generator/backend/AbstractServiceGenerator.java
  PluginDevelopment/src/myplugin/generator/backend/ConcreteDTOGenerator.java
  PluginDevelopment/src/myplugin/generator/backend/ControllerGenerator.java
  PluginDevelopment/src/myplugin/generator/backend/ModelGenerator.java
  PluginDevelopment/src/myplugin/generator/backend/RepositoryGenerator.java
  PluginDevelopment/src/myplugin/generator/backend/ServiceGenerator.java
Labels: enhancement

#32 refactor: separate static files into folders
  PluginDevelopment/resources/ProjectOptions.xml
  PluginDevelopment/resources/static/backend/mvn/MavenWrapperDownloader.java
  PluginDevelopment/resources/static/backend/mvn/maven-wrapper.properties
  PluginDevelopment/src/myplugin/generator/backend/ModelGenerator.java
Labels: refactoring

#30 Bugfix referenced property annotations
  PluginDevelopment/resources/ProjectOptions.xml
  PluginDevelopment/resources/templates/backend/appProperties.ftl
  PluginDevelopment/resources/templates/backend/model.ftl
  PluginDevelopment/src/myplugin/analyzer/ModelAnalyzer.java
  PluginDevelopment/src/myplugin/analyzer/PropertyAnalyzer.java
  PluginDevelopment/src/myplugin/generator/config/AppPropertiesGenerator.java
  PluginDevelopment/src/myplugin/generator/fmmodel/FMApplication.java
  fast-commerc/mbrs-backend-profile.mdzip
  fast-commerc/mbrs-example.mdzip
Labels: DON'T MERGE, bug
